services:
  postgres: 
    container_name: todolist_db
    image: postgres:13
    environment:
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports: 
      - "5432:5432"

volumes:
  postgres-db:
    driver: local